### ISSUE TITLE
Cannot parse mpileup lines from pileup

### ISSUE THREAD

**Issue by batelz** [Paleogenomics/compare-vcf2bam#1]
When running IBDGem, I get the following error:
```
[::] ERROR in init_Pu_chr(): Cannot parse mpileup lines from S123.
[::] ERROR parsing Pileup data; make sure input is valid.
```

S123 was produced by using the commands in your manual, and looks like this (single sample):
1       10210   N       1       ^8T     J
1       10211   N       1       A       J
1       10212   N       1       A       J
1       10213   N       1       C       J
1       10214   N       1       C       J
1       10215   N       1       C       J
1       10216   N       1       T       J
1       10217   N       1       A       J
1       10218   N       1       A       J
1       10219   N       1       C       J
1       10220   N       1       C       J
1       10221   N       1       C       J
1       10222   N       1       T       J
1       10223   N       1       A       J
1       10224   N       1       A       J
1       10225   N       1       C       J
1       10226   N       1       C       J
1       10227   N       1       C       J
1       10228   N       1       T       J
1       10229   N       1       A       J
1       10230   N       1       A       J
1       10231   N       1       C       J
1       10232   N       1       C       J
1       10233   N       1       C       J
1       10234   N       1       T       J
1       10235   N       1       T       J

Can you help with fixing this problem?

**Comment by edgreen72** [comment]
mpileup should be run with -s flag (output mapping quality). The mpileup parser expects this. The mpileup output should have 7 columns.
TODO: Add this requirement to the manual.

**Comment by remynhn** [comment]
The -s/--output-MQ flag has been added to the samtools mpileup example command in the manual.

**Comment by batelz** [comment]
Thank you for your fast response.
I've ran with the -s argument.

Now the error is different:
`mpileup lines not sorted!`

**Comment by remynhn** [comment]
Looks like the original BAM was not sorted, you can try running:
`samtools sort {in.bam} | samtools mpileup -s -o {out.pileup} -`

**Comment by batelz** [comment]
I've already sorted the sequences, as follows:

```
bam=/bam/S123.bam
sortedBam=/bam/sorted.S123.bam
samtools sort $bam -o $sortedBam
out_pileup=/IBDGem/S2123
samtools mpileup $sortedBam -s -o $out_pileup
```

Then:
`/IBDGem/IBDGem-2.0.2/ibdgem -V ${path}${out}.vcf -P $out_pileup
`
```
mpileup lines not sorted!
[::] ERROR parsing Pileup data; make sure input is valid.
```

**Comment by remynhn** [comment]
Does your Pileup file contain multiple chromosomes? If so, and the VCF is already single-chromosome, include `-c {chromosome-name}` in your IBDGem command to specify which chromosome to run on (the program is designed be run on one chromosome at a time - will update manual to clarify this). The command will look something like this:
`/IBDGem/IBDGem-2.0.2/ibdgem -V {in.chr1.vcf} -P {in.pileup} -c chr1`

If the VCF also contains multiple chromosomes, it should be divided into single-chromosome files before running IBDGem (the Pileup file doesn't need to be subdivided, simply use the `-c` option like above). You can subset the VCF using `vcftools` with the `--chr` option.

**Comment by batelz** [comment]
We are having progress... 

So I've seperated the VCF by chromosome. 
When trying to run IBDGem on chr22, like so:
`/softwares/IBDGem/IBDGem-2.0.2/ibdgem -c 22 -V chr22.allhms.IBDGem.vcf.recode.vcf -P $out_pileup`
I get:
```
Running UNKWN-vs-1_ comparison...
Failed to parse genotype fields at 16918335. Skipping to next site.
Failed to parse genotype fields at 17032698. Skipping to next site.
Failed to parse genotype fields at 17054720. Skipping to next site.
Failed to parse genotype fields at 17057138. Skipping to next site.
Failed to parse genotype fields at 17075353. Skipping to next site.
Failed to parse genotype fields at 17087656. Skipping to next site.
Failed to parse genotype fields at 17099107. Skipping to next site.
Failed to parse genotype fields at 17104369. Skipping to next site.
Failed to parse genotype fields at 17152611. Skipping to next site.
Failed to parse genotype fields at 17154984. Skipping to next site.
..... (This goes on for all positions in chr 22)
Failed to parse genotype fields at 51175626. Skipping to next site.
Failed to parse genotype fields at 51176347. Skipping to next site.
Failed to parse genotype fields at 51177526. Skipping to next site.
Failed to parse genotype fields at 51177541. Skipping to next site.
Failed to parse genotype fields at 51178090. Skipping to next site.
Running UNKWN-vs-2_ comparison...
/var/spool/slurmd/job21938876/slurm_script: line 4: 114854 Segmentation fault 
```

The genotype looks like this
`vcftools --chr 22 --from-bp 51177526 --to-bp 51178090 --recode --stdout --vcf chr22.allhms.IBDGem.vcf.recode.vcf
````
##fileformat=VCFv4.2
##fileDate=20240307
##source=PLINKv1.90
##contig=<ID=1,length=249210708>
##contig=<ID=2,length=243044148>
##contig=<ID=3,length=197836413>
##contig=<ID=4,length=190897285>
##contig=<ID=5,length=180690938>
##contig=<ID=6,length=170909003>
##contig=<ID=7,length=159119487>
##contig=<ID=8,length=146296415>
##contig=<ID=9,length=141039841>
##contig=<ID=10,length=135434304>
##contig=<ID=11,length=134942907>
##contig=<ID=12,length=133840843>
##contig=<ID=13,length=115103151>
##contig=<ID=14,length=107287664>
##contig=<ID=15,length=102398061>
##contig=<ID=16,length=90149923>
##contig=<ID=17,length=81041078>
##contig=<ID=18,length=78016634>
##contig=<ID=19,length=59087480>
##contig=<ID=20,length=62912464>
##contig=<ID=21,length=48100156>
##contig=<ID=22,length=51178091>
##contig=<ID=23,length=155234383>
##contig=<ID=24,length=59033250>
##INFO=<ID=PR,Number=0,Type=Flag,Description="Provisional reference allele, may not be based on real reference genome">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  1_  2_        3_       4_       5_       6_     7_    8_     9_     10_    11_        12_        13_      14_    15_        16_
22      51177526        rs116026001     G       A       .       .       .       GT      1/1     1/1     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.  ./.      1/1     ./.
22      51177541        Affx-50065629   T       C       .       .       .       GT      1/1     1/1     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.  ./.      ./.     ./.
22      51178090        rs2285395       A       G       .       .       .       GT      1/1     1/1     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.     ./.  ./.      1/1     ./.
```

**Comment by remynhn** [comment]
Thank you for being patient with the errors. When parsing VCFs, IBDGem will skip sites with missing genotypes (`./.`) and other genotypes it considers invalid (for example, genotypes where the encoded alleles are not `0` or `1`, like `0/2`). This is because by default, it will compare the Pileup data to each one of the samples in the VCF, at every site, so all genotypes have to be available.

A way to maximize the number of compared sites per sample is to subset the VCF by sample, and supply a separate allele frequency file with 3 columns: `CHROM`, `POS`, `FREQ` (no header) through the `-A` option. This is so that the program can use the provided allele frequencies in its calculations instead of having to estimate them from the genotypes in the VCF. The command will look something like this:
`/IBDGem/IBDGem-v2.0.2/ibdgem -V {input.sample1.chr1.vcf} -P {input.pileup} -c chr1 -A {background.AF.txt}`
